[package]
name = "simple-cdc-reader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12", features = ["full"] }
scylla = "0.2.1"
chrono = "0.4.19"
hex = "0.4.3"